[package]
name = "server"
version = "0.1.0"
edition = "2021"

[lib]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0-rc.2"
rocket-multipart-form-data = "0.10.5"
lzw = { path = "../lzw" }
bytes = "1.3.0"
